import Head from "next/head";
import About from "../components/About";
import Banner from "../components/Banner";
import CreatNSell from "../components/CreatNSell";
import DiscoverMore from "../components/DiscoverMore";
import Features from "../components/Features";
import Footer from "../components/Footer";
import Navigation from "../components/Navigation";
import NftStates from "../components/NftStates";
export default function Home() {
  return (
    <div className="">
      <Head>
        <title>NFT-playground</title>
        <meta
          name="nft, crypto wep app"
          content="Generated by create next app @rid1xyz"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      {/* BannerHeading */}
      <Banner />
      {/* About section */}
      <About />
      {/* NFT states */}
      <NftStates />
      {/* Featured Collection */}
      <Features />
      {/* Create and sell sections */}
      <CreatNSell />
      {/* Discover More Sections */}
      <DiscoverMore />
      {/* Footer */}
      <Footer />
    </div>
  );
}
