import Head from "next/head";
import Image from "next/image";
import Navigation from "../components/Navigation";
export default function Home() {
  return (
    <div className="max-w-8xl mx-20 px-4">
      <Head>
        <title>NFT-playground</title>
        <meta
          name="nft, crypto wep app"
          content="Generated by create next app @rid1xyz"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />

      {/* BannerHeading */}

      {/* About section */}

      {/* NFT states */}

      {/* Featured Collection */}

      {/* Create and sell sections */}

      {/* Discover More Sections */}

      {/* Footer */}
    </div>
  );
}
