import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="text-red">
      <Head>
        <title>NFT-playground</title>
        <meta name="nft, crypto wep app" content="Generated by create next app @rid1xyz" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold text-indigo underline">Hello world!</h1>
    </div>
  );
}
